# Version control for tyk apis and policies
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-app-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LLe27/argocd-demo.git'
    path: resources
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true
  #   automated:
  #     selfHeal: true
  #     prune: true
---
# Cert-manager application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.0
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Tyk-Operator application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.tyk.io/public/helm/charts'
    targetRevision: 0.13.0
    chart: tyk-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tyk-operator-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
